//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackPad
        {
            get
            {
                return SteamVR_Actions.default_TrackPad;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackPadClick
        {
            get
            {
                return SteamVR_Actions.default_TrackPadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackPadTouch
        {
            get
            {
                return SteamVR_Actions.default_TrackPadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.default_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerTouch
        {
            get
            {
                return SteamVR_Actions.default_TriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerPull
        {
            get
            {
                return SteamVR_Actions.default_TriggerPull;
            }
        }
        
        public virtual SteamVR_Action_Boolean AButton
        {
            get
            {
                return SteamVR_Actions.default_AButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean AButtonTouch
        {
            get
            {
                return SteamVR_Actions.default_AButtonTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean BButton
        {
            get
            {
                return SteamVR_Actions.default_BButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean BButtonTouch
        {
            get
            {
                return SteamVR_Actions.default_BButtonTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ThumbStick
        {
            get
            {
                return SteamVR_Actions.default_ThumbStick;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbStickClick
        {
            get
            {
                return SteamVR_Actions.default_ThumbStickClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbStickTouch
        {
            get
            {
                return SteamVR_Actions.default_ThumbStickTouch;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
